### ISSUE TITLE
Vertical WiModem probably not Tandy 200 compatible

### ISSUE THREAD

**Issue by hackerb9** [bkw777/WiModem_to_100#1]
The README mentions that your slick design for attaching a WiModem vertically is compatible with the Tandy 200. However, I would think that the lid/screen would bonk into the WiModem. No?

**Comment by bkw777** [comment]
I think you may be right. I'll have to check when I get home. You can flip the adapter around and that makes the wimodem stand a little further away from the computer instead of right against it. That might be just enough. Otherwise, maybe the directions for 200 should just be the same as for 102. IE just use a regular mini gender-changer, because if you can't see the wimodem behind the screen anyway, then it doesn't matter much if the led is facing up or down.

I'll update the readme when I get a chance to look at my 200.

**Comment by bkw777** [comment]
I have checked it out with my 200 now.
It's mostly ok.

If you install the adapter one way with the wimodem closest to the 200, then the screen still does not hit the wimodem when the screen is at the detent angle, but does hit the wimodem when you open the screen past the detent to the end of it's travel, but even then, not bad enough to hurt. It pushes the top of the wimodem back about 1/4". Not enough to even bend the pins in the connectors. Although definitely the connections are no longer straight.

If you install the adapter the other way, the wimodem is both further away from the back of the 200, and lower too, and then the screen just barely touches the wimodem when you open the screen as far as possible, even with a right-angle usb cord plugged in.

A straight usb plug in the wimodem makes both of those worse.

However, like I imagined before, since the wimodem is behind the screen, there isn't much reason to use this adapter anyway on a 200, since you can't see the wimodem anyway. You might as well just use a regular mini gender-changer. Or, if you want to see the led or the oled, then you'll need a 25-pin cable anyway to relocate the wimodem out from behind the screen. In either case you still don't need this adapter to provide the gender-change and don't need the 90-degree.

But, just for completeness, the orientation of the "D" shape of the db25 connector on the 200 is correct for this adapter, so the wimodem stands up away from the table not pointing down into it (like what would happen on a 102)
and you might possibly still want to use this adapter just for safety and to reduce the desktop footprint. The wimodem laying straight out from the back of the 200 takes up more desktop and is at risk of being stressed.

**Comment by hackerb9** [comment]
Thanks for trying it out.  I think you are correct that a 200 user would want to use the adapter in the second configuration just to keep the desk footprint smaller. The risk of stress is significant and would be moreso for people who use their 200s on their laps.
